default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: '!fodel1234'
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: langdy_development

test:
  <<: *default
  database: test_db_name

production:
  <<: *default
  database: production_db_name
